"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.wordPackRegistry = void 0;
exports.wordPackRegistry = {
    en: {
        classic: ["AGENT", "AIR", "ALIEN", "ALPS", "AMAZON", "AMBULANCE", "AMERICA", "ANGEL", "ANTARCTICA", "APPLE", "ARM", "ATLANTIS", "AUSTRALIA", "AZTEC", "BACK", "BALL", "BAND", "BANK", "BAR", "BARK", "BAT", "BATTERY", "BEACH", "BEAR", "BEAT", "BED", "BEIJING", "BELL", "BELT", "BERLIN", "BERMUDA", "BERRY", "BILL", "BLOCK", "BOARD", "BOLT", "BOMB", "BOND", "BOOM", "BOOT", "BOTTLE", "BOW", "BOX", "BRIDGE", "BRUSH", "BUCK", "BUFFALO", "BUG", "BUGLE", "BUTTON", "CALF", "CANADA", "CAP", "CAPITAL", "CAR", "CARD", "CARROT", "CASINO", "CAST", "CAT", "CELL", "CENTAUR", "CENTER", "CHAIR", "CHANGE", "CHARGE", "CHECK", "CHEESE", "CHERRY", "CHICK", "CHOCOLATE", "CHURCH", "CIRCLE", "CLIFF", "CLOAK", "CLUB", "CODE", "COLD", "COMIC", "COMPOUND", "CONCERT", "CONDUCTOR", "CONTRACT", "COOK", "COPPER", "COTTON", "COURT", "COVER", "CRANE", "CRASH", "CRICKET", "CROSS", "CROWN", "CYCLE", "CZECH", "DANCE", "DATE", "DAY", "DEATH", "DECK", "DEGREE", "DIAMOND", "DICE", "DINOSAUR", "DISEASE", "DOCTOR", "DOG", "DRAFT", "DRAGON", "DRESS", "DRILL", "DROP", "DUCK", "DWARF", "EAGLE", "EGYPT", "EMBASSY", "ENGINE", "ENGLAND", "EUROPE", "EYE", "FACE", "FAIR", "FALL", "FAN", "FENCE", "FIELD", "FIGHTER", "FIGURE", "FILE", "FILM", "FIRE", "FISH", "FLUTE", "FLY", "FOOT", "FORCE", "FOREST", "FORK", "FRANCE", "GAME", "GAS", "GENIUS", "GERMANY", "GHOST", "GIANT", "GLASS", "GLOVE", "GOLD", "GRACE", "GRASS", "GREECE", "GREEN", "GROUND", "HAM", "HAND", "HAWK", "HEAD", "HEART", "HELICOPTER", "HIMALAYAS", "HOLE", "HOLLYWOOD", "HONEY", "HOOD", "HOOK", "HORN", "HORSE", "HOSPITAL", "HOTEL", "ICE", "ICE CREAM", "INDIA", "IRON", "IVORY", "JACK", "JAM", "JET", "JUPITER", "KANGAROO", "KETCHUP", "KEY", "KID", "KING", "KIWI", "KNIFE", "KNIGHT", "LAB", "LAP", "LASER", "LAWYER", "LEAD", "LEMON", "LEPRECHAUN", "LIFE", "LIGHT", "LIMOUSINE", "LINE", "LINK", "LION"],
        duet: ["LITTER", "LOCH NESS", "LOCK", "LOG", "LONDON", "LUCK", "MAIL", "MAMMOTH", "MAP", "MARBLE", "MARCH", "MASS", "MATCH", "MERCURY", "MEXICO", "MICROSCOPE", "MILLIONAIRE", "MINE", "MINT", "MISSILE", "MODEL", "MOLE", "MOON", "MOSCOW", "MOUNT", "MOUSE", "MOUTH", "MUG", "NAIL", "NEEDLE", "PYRAMID", "QUEEN", "RABBIT", "RADAR", "RAY", "REVOLUTION", "RING", "ROBIN", "ROBOT", "ROCK", "ROME", "ROOT", "ROSE", "ROULETTE", "ROUND", "ROW", "RULER", "SATELLITE", "SATURN", "SCALE", "SCHOOL", "SCIENTIST", "SCORPION", "SCREEN", "SCUBA DIVER", "SEAL", "SERVER", "SHADOW", "SHAKESPEARE", "SHARK", "SHIP", "SHOE", "SHOP", "SHOT", "SINK", "SKYSCRAPER", "SLIP", "SLUG", "SMUGGLER", "SNOW", "SNOWMAN", "SOCK", "SOLDIER", "SOUL", "SOUND", "SPACE", "SPELL", "SPIDER", "SPIKE", "SPINE", "SPOT", "SPRING", "SPY", "SQUARE", "STADIUM", "STAFF", "STAR", "STATE", "STICK", "STOCK", "STRAW", "STREAM", "STRIKE", "STRING", "SUB", "SUIT", "SUPERHERO", "SWING", "SWITCH", "SWORD", "TABLE", "TABLET", "TAG", "TAIL", "TAP", "TEACHER", "TELESCOPE", "TEMPLE", "THEATER", "THIEF", "THUMB", "TICK", "TIE", "TIME", "TOKYO", "TOOTH", "TORCH", "TOWER", "TRACK", "TRAIN", "TRIANGLE", "TRIP", "TRUNK", "TUBE", "TURKEY", "UNDERTAKERS", "UNICORN", "VACUUM", "VAN", "VET", "WAKE", "WALL", "WAR", "WASHER", "WATCH", "WATER", "WAVE", "WEB", "WELL", "WHALE", "WHIP", "WIND", "WITCH", "WORM", "YARD", "OCEAN", "PLANET", "MUSEUM", "CASTLE", "GALAXY", "JOURNEY", "SILVER", "PLATINUM", "CRYSTAL", "SHIELD", "ARMOR", "PIRATE", "ZOMBIE", "VAMPIRE", "ORBIT", "COMET", "ASTEROID", "METEOR", "GRAVITY", "ECLIPSE", "HORIZON", "DAWN", "DUSK", "TWILIGHT", "MIDNIGHT", "NOON", "AFTERNOON", "MORNING", "SUMMER", "AUTUMN", "WINTER", "SEASON", "DECADE", "CENTURY", "MILLENNIUM"]
    },
    ar: {
        classic: ["عميل", "هواء", "فضائي", "جبال الألب", "أمازون", "إسعاف", "أمريكا", "ملاك", "القارة القطبية", "تفاحة", "ذراع", "أتلانتس", "أستراليا", "أزتيك", "ظهر", "كرة", "فرقة", "بنك", "شريط", "لحاء", "خفاش", "بطارية", "شاطئ", "دب", "إيقاع", "سرير", "بكين", "جرس", "حزام", "برلين", "برمودا", "توت", "فاتورة", "كتلة", "لوحة", "مسمار", "قنبلة", "رابطة", "ازدهار", "حذاء", "زجاجة", "قوس", "صندوق", "جسر", "فرشاة", "غزال", "جاموس", "حشرة", "بوق", "زر", "عجل", "كندا", "قبعة", "عاصمة", "سيارة", "بطاقة", "جزرة", "كازينو", "طاقم", "قطة", "خلية", "قنطور", "مركز", "كرسي", "تغيير", "تهمة", "فحص", "جبن", "كرز", "صوص", "شوكولاتة", "كنيسة", "دائرة", "جرف", "عباءة", "نادي", "شفرة", "برد", "هزلي", "مركب", "حفلة", "قائد", "عقد", "طباخ", "نحاس", "قطن", "محكمة", "غطاء", "رافعة", "تحطم", "كريكيت", "صليب", "تاج", "دورة", "تشيكي", "رقصة", "تاريخ", "يوم", "موت", "سطح", "درجة", "ألماس", "نرد", "ديناصور", "مرض", "طبيب", "كلب", "مسودة", "تنين", "فستان", "حفر", "قطرة", "بطة", "قزم", "نسر", "مصر", "سفارة", "محرك", "إنجلترا", "أوروبا", "عين", "وجه", "عادل", "خريف", "مروحة", "سياج", "حقل", "مقاتل", "شكل", "ملف", "فيلم", "نار", "سمكة", "مزمار", "ذبابة", "قدم", "قوة", "غابة", "شوكة", "فرنسا", "لعبة", "غاز", "عبقري", "ألمانيا", "شبح", "عملاق", "زجاج", "قفاز", "ذهب", "نعمة", "عشب", "اليونان", "أخضر", "أرض", "لحم", "يد", "صقر", "رأس", "قلب", "مروحية", "هيمالايا", "حفرة", "هوليوود", "عسل", "غطاء", "خطاف", "قرن", "حصان", "مستشفى", "فندق", "جليد", "آيس كريم", "الهند", "حديد", "عاج", "مقبس", "مربى", "طائرة", "مشتري", "كنغر", "كاتشب", "مفتاح", "طفل", "ملك", "كيوي", "سكين", "فارس", "مختبر", "لفة", "ليزر", "محامي", "رصاص", "ليمون", "جني", "حياة", "ضوء", "ليموزين", "خط", "رابط", "أسد"],
        duet: ["قمامة", "لوخ نيس", "قفل", "جذع", "لندن", "حظ", "بريد", "ماموث", "خريطة", "رخام", "مسيرة", "كتلة", "مباراة", "عطارد", "المكسيك", "مجهر", "مليونير", "لغم", "نعناع", "صاروخ", "نموذج", "شامة", "قمر", "موسكو", "جبل", "فأر", "فم", "كوب", "ظفر", "إبرة", "هرم", "ملكة", "أرنب", "رادار", "شعاع", "ثورة", "خاتم", "عصفور", "روبوت", "صخرة", "روما", "جذر", "وردة", "روليت", "جولة", "صف", "مسطرة", "قمر صناعي", "زحل", "مقياس", "مدرسة", "عالم", "عقرب", "شاشة", "غواص", "فقمة", "خادم", "ظل", "شكسبير", "قرش", "سفينة", "متجر", "طلقة", "مغسلة", "ناطحة سحاب", "زلة", "بزاق", "مهرب", "ثلج", "رجل ثلج", "جورب", "جندي", "روح", "صوت", "فضاء", "تعويذة", "عنكبوت", "عمود فقري", "بقعة", "زنبرك", "جاسوس", "مربع", "ملعب", "عصا", "نجمة", "ولاية", "مخزون", "قشة", "جدول", "إضراب", "خيط", "غواصة", "بدلة", "بطل خارق", "أرجوحة", "سيف", "طاولة", "جهاز لوحي", "علامة", "ذيل", "صنبور", "معلم", "تلسكوب", "معبد", "مسرح", "لص", "إبهام", "قراد", "ربطة عنق", "وقت", "طوكيو", "سن", "شعلة", "برج", "مسار", "قطار", "مثلث", "رحلة", "أنبوب", "ديك رومي", "متعهد", "وحيد القرن", "مكنسة", "شاحنة", "بيطري", "استيقاظ", "جدار", "حرب", "غسالة", "ساعة", "ماء", "موجة", "شبكة", "بئر", "حوت", "سوط", "رياح", "ساحرة", "دودة", "ساحة", "محيط", "كوكب", "متحف", "قلعة", "مجرة", "فضة", "بلاتين", "كريستال", "درع", "قرصان", "زومبي", "مصاص دماء", "مدار", "مذنب", "كويكب", "نيزك", "جاذبية", "كسوف", "أفق", "فجر", "غسق", "شفق", "منتصف الليل", "ظهر", "عصر", "صباح", "صيف", "صيف", "موسم", "عقد", "قرن", "ألفية"]
    }
};
//# sourceMappingURL=wordPacks.js.map